### ISSUE TITLE
[Question] Why is compiled erlang functions is in the following format?

### ISSUE THREAD

**Issue by hariroshan** [purerl/purerl#11]
Hello,
I wrote a simple PureScript function
```
hello :: Int -> Maybe Int
hello 1 = Just 1
hello 2 = Just 2
hello  _ = Nothing
```
And Purerl compiled it to
```
hello() -> fun
  (1) -> 
  { just, 1 };
  (2) -> 
  { just, 2 };
  (_) -> 
  (data_maybe@ps:'Nothing'())
end.
-file("D:\reason\nut_runner\apps\core\src\Main.purs", 9).
hello(_@0) -> (fun
  (1) -> 
  { just, 1 };
  (2) -> 
  { just, 2 };
  (_) -> 
  (data_maybe@ps:'Nothing'())
end(_@0)).

```
Instead of something like 
```
hello(1) -> { just, 1 };
hello(2) -> { just, 2 };
hello(_) -> (data_maybe@ps:'Nothing'()).
```
Also case expressions are also converted into the above format. Is there any reason for using this pattern instead of the mentioned pattern?

**Comment by nwolverson** [comment]
Firstly we generate two overloads of everything, the `hello/0` is the canonical form of any top level binding of `hello`, we also generate an uncurried form, in this case the `hello/1`, depending on the arity of the binding. Can have a look at `hello = 42` and `add a b = a+b` to see how this plays out with different arities.

There's no reason we don't pull up the pattern match to the top level other than it's work to no particular benefit (until someone comes along with a benchmark showing it would be useful of course.)

For case expressions - now there there is a reason they are compiled to a `fun` and not simply a `case`, which is that only a `fun` will introduce fresh variables - a case can cause accidental unification to an already bound variable.

**Comment by hariroshan** [comment]
Thank you for your reply 😄

**Comment by hariroshan** [comment]
I tried the `add` function. It generated the following
```
for something like
add x y = x + y


addM() -> fun (DictSemiring) ->
  fun (A) ->
    fun (B) ->
      (data_semiring@ps:add(DictSemiring, A, B))
    end
  end
end.
-file("D:\reason\nut_runner\apps\core\src\Main.purs", 17).
addM(_@2,_@3,_@4) -> (data_semiring@ps:add(_@2, _@3, _@4)).

```
suppose if i want to use this in repl, how can i pass the first parameter. It say it needs a Semiring Dict.
Thanks

**Comment by hariroshan** [comment]
Never mind I found out 😄 . I looked into the `semiring` module and found a function `semiringInt()`

**Comment by nwolverson** [comment]
I would advise against trying to interface with any functions with typeclass constraints from erlang, instead create an entrypoint with no constraints which you could call - this is just as for standard PureScript advice for JS interop.

E.g.

```
add :: Int -> Int -> Int
add x y = x + y
```
As now the `add` signature does not have any constraints, it will be compiled without that parameter required

(You may find how the representation of typeclass dictionaries is but it's "at your own risk" etc :D )

**Comment by hariroshan** [comment]
Thanks for your comments 🥳 😄

**Comment by hariroshan** [comment]
Are there any examples for genserver behaviour implementation in purescript? I did came across Pinto library. What is your suggestion?

**Comment by nwolverson** [comment]
I'd have a look at https://github.com/id3as/demo-ps
