### ISSUE TITLE
[Feature Request] Are there any plans to  include typespecs along with compiled erlang functions?

### ISSUE THREAD

**Issue by hariroshan** [purerl/purerl#12]
Hello
Type specs makes the code more readable and helpful in debugging while using the purerl compiled functions from other projects. Are any plans in the future to include it ? Also it helps the dialyzer as well.
Thanks,

**Comment by nwolverson** [comment]
That's definitely something I thought of, I guess I never considered the pay-off particularly great as I wouldn't tend to use many entry points in purerl code, more of a main application

Out of curiousity, are you using purerl more as "library code" that you call in many places?

**Comment by hariroshan** [comment]
I'm thinking about keeping the core business logic and other pure function things in purerl and use OTP and Supervisors to use that module.

**Comment by hariroshan** [comment]
@nwolverson  Are there any support to pattern match Map with String key, like `#{"foo" => a}`

**Comment by nwolverson** [comment]
@hariroshan I don't think that last point is related to this issue of typespecs?

PureScript records correspond to erlang maps where the key is an atom, and if you want to use that correspondance you can pattern match on those; alternately, other types of *heterogenous* erlang map can be represented as `Erl.Data.Map`, e.g. `Map String Int` (though of course a PureScript string is an erlang binary string) - though you cannot pattern match on that, and would have to use accessors.

There will not be any support for pattern matching that would require an extension to the PureScript language itself, as this is purely a backend

**Comment by hariroshan** [comment]
Yea It is not related to the issue I wanted to ask. So what about typespecs ? Are there any plans to add them? 😄  @nwolverson

**Comment by nwolverson** [comment]
Yes, I plan for typespecs to be in the next release. They will naturally not cover everything, so I expect they may gradually improve over time, but at least we should get the shape of functions down and primitives etc

**Comment by nwolverson** [comment]
Closing as this is in master now
