### ISSUE TITLE
Warnings on 'unused' definitions in foreign module

### ISSUE THREAD

**Issue by srstrong** [purerl/purerl#15]
There's a helpful warning on exported functions in foreign modules that are not referenced as foreign imports in the corresponding purs file.  However, there are times when this is expected (for example, if the ffi module is hosting a gen_server, at which point it needs exports for handle_call, handle_cast etc).  It would be good to have some marker in the ffi code to indicate to purerl that specific functions are expected to be exported and not referenced in the purs.  Perhaps some sort of attribute, e.g.

`-non_purs_functions([handle_call/3, handle_cast/3]).`

**Comment by nwolverson** [comment]
This was added as `purs_ignore_exports`
