### ISSUE TITLE
Calling Elixir functions from purerl

### ISSUE THREAD

**Issue by disappearer** [purerl/purerl#23]
Hello and thank you for bringing Purescript to BEAM!

I'm not sure if this is the right place to ask and if it's not - feel free to ignore my question and close the issue.

I wish to use Purescript to write the core of my application which is currently written in Elixir. I've managed to call purerl functions from Elixir, but I'm not sure how to do it the other way around. Is it at all possible to call Elixir functions from purerl and if so, how would I go about it?

**Comment by nwolverson** [comment]
To do that you will need to write an [Erlang FFI function](https://github.com/purerl/purerl#ffi) which calls your Elixir function. This would be then the same problem as calling Elixir from Erlang generally - [example here](https://blog.oestrich.org/2017/07/call-elixir-from-erlang/) which seems straightforward enough.

**Comment by disappearer** [comment]
Thank you for your reply. That was the way I eventually ended up trying, but I got stuck with the setup of the compilers. Since that has nothing to do with purerl I will close the issue.
