### ISSUE TITLE
Nested do blocks causes error in erlang compilation

### ISSUE THREAD

**Issue by EMattfolk** [purerl/purerl#26]
I found a small program that works with the js backend but not purerl. It might be worth looking into.

```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  a <- do
    a <- do
      a <- pure unit
      pure a
    pure a
  log "Oh no"
```

From what I gather it only happens when there is this much nesting or more. It works fine if you remove a layer.
The generated code looks something like this:

```erlang
a = begin
  a@1 = unit,
  a@0
end,
```

This produces an error that says variable 'a@0' is unbound

Here is the generated JS for reference
```js
var main = function __do() {
    var a = (function __do() {
        var a = (function __do() {
            return Data_Unit.unit;
        })();
        return a;
    })();
    return Effect_Console.log("Oh no")();
};
```

**Comment by robashton** [comment]
Don't know if it's the same bug, but dumping this here so it doesn't get lost

```
module A where

f :: Int
f = case {q: [1] } of
      { q: [x] } -> x
      _ -> 0
```

results in the 


```
Compiling 1 file (.erl)
/workspace/lib/A.purs:6:18: variable '_@0' is unbound
%    6|       _ -> 0
%     |             ^^^^^^
```

dance as well

**Comment by robashton** [comment]
Note: 

This actually impacts any case statement where we're unpacking an array when it's contained within a map (record).

```
case a of 
  { q: [a,b] } -> a + b
  _ -> 0
```


Will result in

```
output/A/a@ps.erl:19:24: variable '_@1' is unbound
%   19|   (#{q:=_@2}) -> _@0 + _@1;
%     |                        ^
```

The short answer in this example, is "Don't use Arrays", which is sound advice for anything written in Purerl because of the performance implications.

Also, this is likely to be a V different bug to the original submitted.
