### ISSUE TITLE
Effect.Aff : is it relevant?

### ISSUE THREAD

**Issue by hasanalrasyid** [purerl/purerl#35]
Hello, thank you for this great implementation.

I do not know whether this is a correct place to ask this. So please bear with me.

So, right now, I am looking at a purescript library that lives under Effect.Aff (purescript-mongo). My plan was to straight away put everything under Effect. Is this a correct way to do this?

Are there a more elegant way to do this reimplementation? Any pointers would be very much appreciated. Thank you very much.

**Comment by nwolverson** [comment]
There is no implementation of `Aff` in purerl at this point, which is not to say that it might not be useful at times, but generally what might be written in `Aff` in JS, in the context of async computation of some sort in a single-threaded runtime, is often expressed in erlang simply as multiple communicating processes (spawned processes, gen servers, etc) which may each block.

If you look at the JS implementation of Aff, you can see that it is non-trivial to correctly match in another runtime, so the cost has not been worth any use that has been considered so far.

And your example of database bindings - yes I'd expect that would naturally just work well in `Effect` in this context

**Comment by hasanalrasyid** [comment]
Okay, thank you for the insight. I think I can close this issue and create more detailed ones when I got some problem on it. 

Cheers ...
