### ISSUE TITLE
How to upgrade a purerl package set?

### ISSUE THREAD

**Issue by FranklinChen** [purerl/purerl#9]
I had manually edited `packages.dhall` to have

```
let upstream =
      https://raw.githubusercontent.com/purerl/package-sets/erl-0.13.5-20191204/src/packages.dhall sha256:308bc2dd2c5700e6e22fae85b10472fd76ddaaf8034711ff0eaede145573479a
```

as instructed, but then ran `spago upgrade-set` hoping to get https://github.com/purerl/package-sets/releases/tag/erl-0.13.5-20200707 inserted into `packages.dhall` but that is not what it did. I'm not sure what the correct automated way is to upgrade the package set, if there is one.

**Comment by nwolverson** [comment]
I don't think there's an automated way to update the package set, this probably requires work on spago to enable that command to not be tied to the default package set.

For now I recommend just inserting the package set you want, delete the hash, and let spago update the hash appropriately

**Comment by FranklinChen** [comment]
OK, got it.
